ex06_index:
    path: /ex06
    controller: App\Controller\Ex06Controller::index
    methods: [GET]

ex06_insert_user:
    path: /ex06/insert_user
    controller: App\Controller\Ex06Controller::insertUser
    methods: [POST]

ex06_delete_user:
    path: /ex06/delete_user/{id}
    controller: App\Controller\Ex06Controller::deleteUser
    methods: [POST]

ex06_delete_all_users:
    path: /ex06/delete_all_users
    controller: App\Controller\Ex06Controller::deleteAllUsers
    methods: [POST]