ex08_index:
    path: /ex08
    controller: App\Controller\Ex08Controller::index
    methods: [GET]

ex08_create_persons_table:
    path: /ex08/create_persons_table
    controller: App\Controller\Ex08Controller::createPersonsTable
    methods: [POST]

ex08_create_bank_accounts_table:
    path: /ex08/create_bank_accounts_table
    controller: App\Controller\Ex08Controller::createBankAccountsTable
    methods: [POST]

ex08_create_relation_bank_account:
    path: /ex08/create_relation_bank_account
    controller: App\Controller\Ex08Controller::createBankAccountRelation
    methods: [POST]

ex08_create_addresses_table:
    path: /ex08/create_addresses_table
    controller: App\Controller\Ex08Controller::createAddressesTable
    methods: [POST]

ex08_create_relation_addresses:
    path: /ex08/create_relation_addresses
    controller: App\Controller\Ex08Controller::createAddressesRelation
    methods: [POST]

ex08_add_marital_status:
    path: /ex08/add_marital_status
    controller: App\Controller\Ex08Controller::addMaritalStatus
    methods: [POST]

ex08_remove_marital_status:
    path: /ex08/remove_marital_status
    controller: App\Controller\Ex08Controller::removeMaritalStatus
    methods: [POST]