ex08_index:
    path: /ex08
    controller: App\Controller\Ex08Controller::index
    methods: [GET]

ex08_create_persons_table:
    path: /ex08/create_persons_table
    controller: App\Controller\Ex08Controller::createPersonsTable
    methods: [POST]

ex08_create_bank_accounts_table:
    path: /ex08/create_bank_accounts_table
    controller: App\Controller\Ex08Controller::createBankAccountsTable
    methods: [POST]

ex08_create_relation_bank_account:
    path: /ex08/create_relation_bank_account
    controller: App\Controller\Ex08Controller::createBankAccountRelation
    methods: [POST]