ex10_index:
    path: /ex10
    controller: App\Controller\Ex10Controller::index
    methods: [GET]

ex10_insert_data_sql:
    path: /ex10/insert_data_sql
    controller: App\Controller\Ex10Controller::insertDataSQL
    methods: [POST]

ex10_insert_data_orm:
    path: /ex10/insert_data_orm
    controller: App\Controller\Ex10Controller::insertDataORM
    methods: [POST]

ex10_delete_data_sql:
    path: /ex10/delete_data_sql/{id}
    controller: App\Controller\Ex10Controller::deleteDataSQL
    methods: [POST]
    requirements:
        id: '\d+'

ex10_delete_all_data_sql:
    path: /ex10/delete_all_data_sql
    controller: App\Controller\Ex10Controller::deleteAllDataSQL
    methods: [POST]

ex10_delete_data_orm:
    path: /ex10/delete_data_orm/{id}
    controller: App\Controller\Ex10Controller::deleteDataORM
    methods: [POST]
    requirements:
        id: '\d+'

ex10_delete_all_data_orm:
    path: /ex10/delete_all_data_orm
    controller: App\Controller\Ex10Controller::deleteAllDataORM
    methods: [POST]

ex10_delete_all:
    path: /ex10/delete_all
    controller: App\Controller\Ex10Controller::deleteAll
    methods: [POST]

ex10_import_file:
    path: /ex10/import
    controller: App\Controller\Ex10Controller::importFile
    methods: [POST]
