ex02_index:
    path: /ex02
    controller: App\Controller\Ex02Controller::index
    methods: [GET]

ex02_insert_user:
    path: /ex02/insert_user
    controller: App\Controller\Ex02Controller::insertUser
    methods: [POST]

