ex13_index:
    path: /ex13
    controller: App\Controller\Ex13Controller::index
    methods: [GET]

ex13_insert_employees:
    path: /ex13/insert_employees
    controller: App\Controller\Ex13Controller::insertEmployees
    methods: [POST]

ex13_update_employees:
    path: /ex13/update_employees/{id}
    controller: App\Controller\Ex13Controller::updateEmployees
    methods: [GET, POST]
    requirements:
        id: '\d+'

ex13_delete_employees:
    path: /ex13/delete_employees/{id}
    controller: App\Controller\Ex13Controller::deleteEmployees
    methods: [POST]
    requirements:
        id: '\d+'

ex13_delete_all_employees:
    path: /ex13/delete_all_employees
    controller: App\Controller\Ex13Controller::deleteAllEmployees
    methods: [POST]
